apiVersion: v1
kind: ResourceQuota
metadata:
    name: compute-qouta
    namespace: dev
    
spec:
  hard:
    pods: 3
    requests.cpu: "0.5"
    requests.memory: 500Mi
    limits.cpu: "1"
    limits.memory: 1Gi

