apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: throw-dice-cron-job

spec:
  schedule: "30 21 * * *"
  jobTemplate:
    spec:
      template:
       spec:
        containers:
        - image:  kodekloud/throw-dice
          name:   throw-dice
        restartPolicy: Never
 
