apiVersion: apps/v1
kind: Deployment
metadata:
  name:  blue
spec:
  strategy:
   type: Recreate
  
  template:
   metadata:
     name: blue
     labels:
       app: blue
   spec:
    containers:
    - image:  nginx:1.21-err
      name:  nginx
  replicas: 6
  selector:
    matchLabels:
      app: blue
