apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
spec:
  template:
     metadata:
      name: red
      labels: 
       app: red
     spec:
      containers:
      - image:  nginx
        name:  nginx
        imagePullPolicy: Always
      affinity:
        nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: node-role.kubernetes.io/master
               operator: Exist
  replicas: 6
  selector:
    matchLabels:
      app: red   