apiVersion: apps/v1
kind: Deployment
metadata:
  name:  blue
spec:
  template:
   metadata:
     name: blue
     labels:
       app: blue
   spec:
    containers:
    - image:  nginx
      name:  nginx
      imagePullPolicy: Always
    affinity:
     nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: color
            operator: In 
            values:
             - blue
  replicas: 3
  selector:
    matchLabels:
      app: blue
