apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis
spec:
  template:
   metadata:
     name: redis
     labels:
       app: redis
   spec:
    containers:
    - image:  redis:alpine
      name:   redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
