apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-declartive
  annotations:
   environment: prod
   organization: sales
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
