apiVersion: v1
kind: Pod
metadata:
    name: my-web-app-tolerations
spec:
  containers:
  - name: nginx-controller
    image: nginx
  tolerations:
  - key: app
    operator: "Equal"
    value: "my-web-app"
    effect: "NoSchedule"