apiVersion: v1
kind: Pod
metadata:
  name: elephant
spec:
  containers:
  -  image: polinux/stress
     name: elephant
     resources:
       requests:
          memory: 5Mi
       limits:
          memory: 20Mi
         