apiVersion: v1
kind: Pod
metadata:
  name: my-web-ap-affinity
spec:
 containers:
 -  image:  image
    name:  my-name
 affinity:
   nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:  #requiredDuringSchedulingIgnoredDuringExecution,prefeeredDuringSchedulingIgnoredDuringExecution,requiredDuringSchedulingRequiredDuringExecution
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In #NotIn,Exsist
            values:
             - Large
   