apiVersion: v1
kind: Pod
metadata:
   name: my-pod
   labels:
     myapp: app



spec:
  containers:
  - image:  image
    name:  my-name
    env:
      - name:  ENVVARNAME
        value:  ENVVARVALUE